# Generated by Django 3.2.5 on 2021-07-22 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitid', models.AutoField(db_column='circuitId', primary_key=True, serialize=False)),
                ('circuitref', models.CharField(db_column='circuitRef', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('alt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'circuits',
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorid', models.AutoField(db_column='constructorId', primary_key=True, serialize=False)),
                ('constructorref', models.CharField(db_column='constructorRef', max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'constructors',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.AutoField(db_column='driverId', primary_key=True, serialize=False)),
                ('driverref', models.CharField(db_column='driverRef', max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceid', models.AutoField(db_column='raceId', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('circuitid', models.ForeignKey(db_column='circuitId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.circuits')),
            ],
            options={
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(db_column='statusId', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultid', models.AutoField(db_column='resultId', primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(db_column='positionText', max_length=255)),
                ('positionorder', models.IntegerField(db_column='positionOrder')),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestlap', models.IntegerField(blank=True, db_column='fastestLap', null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('fastestlaptime', models.CharField(blank=True, db_column='fastestLapTime', max_length=255, null=True)),
                ('fastestlapspeed', models.CharField(blank=True, db_column='fastestLapSpeed', max_length=255, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.constructors')),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.races')),
                ('statusid', models.ForeignKey(db_column='statusId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.status')),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifyid', models.AutoField(db_column='qualifyId', primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('q1', models.CharField(blank=True, max_length=255, null=True)),
                ('q2', models.CharField(blank=True, max_length=255, null=True)),
                ('q3', models.CharField(blank=True, max_length=255, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.constructors')),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.races')),
            ],
            options={
                'db_table': 'qualifying',
            },
        ),
        migrations.CreateModel(
            name='Driverstandings',
            fields=[
                ('driverstandingsid', models.AutoField(db_column='driverStandingsId', primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.races')),
            ],
            options={
                'db_table': 'driverStandings',
            },
        ),
        migrations.CreateModel(
            name='Constructorstandings',
            fields=[
                ('constructorstandingsid', models.AutoField(db_column='constructorStandingsId', primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.constructors')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.races')),
            ],
            options={
                'db_table': 'constructorStandings',
            },
        ),
        migrations.CreateModel(
            name='Constructorresults',
            fields=[
                ('constructorresultsid', models.AutoField(db_column='constructorResultsId', primary_key=True, serialize=False)),
                ('points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.constructors')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.races')),
            ],
            options={
                'db_table': 'constructorResults',
            },
        ),
        migrations.CreateModel(
            name='Pitstops',
            fields=[
                ('raceid', models.OneToOneField(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='history.races')),
                ('stop', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.drivers')),
            ],
            options={
                'db_table': 'pitStops',
                'unique_together': {('raceid', 'driverid', 'stop')},
            },
        ),
        migrations.CreateModel(
            name='Laptimes',
            fields=[
                ('raceid', models.OneToOneField(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='history.races')),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='history.drivers')),
            ],
            options={
                'db_table': 'lapTimes',
                'unique_together': {('raceid', 'driverid', 'lap')},
            },
        ),
    ]
