# Generated by Django 3.2.5 on 2021-07-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20210725_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivers',
            old_name='dob',
            new_name='birthday',
        ),
    ]
