# Generated by Django 3.2.5 on 2021-07-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_rename_dob_drivers_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuits',
            old_name='url',
            new_name='wiki_url',
        ),
        migrations.RenameField(
            model_name='constructors',
            old_name='url',
            new_name='wiki_url',
        ),
        migrations.RenameField(
            model_name='drivers',
            old_name='url',
            new_name='wiki_url',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='url',
            new_name='wiki_url',
        ),
        migrations.RenameField(
            model_name='seasons',
            old_name='url',
            new_name='wiki_url',
        ),
    ]
