# Generated by Django 3.2.5 on 2021-08-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20210725_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualifying',
            old_name='number',
            new_name='driver_number',
        ),
    ]
